/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerLifycycleRouteImport } from './routes/worker-lifycycle'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmployeeOverviewRouteImport } from './routes/employee-overview'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user/$Id'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsIssueStatusesRouteImport } from './routes/settings/issue-statuses'
import { Route as SettingsEngagementStatusesRouteImport } from './routes/settings/engagement-statuses'
import { Route as SettingsEmployeesRouteImport } from './routes/settings/employees'
import { Route as PasswordResetRouteImport } from './routes/password/reset'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as SettingsTemplatesTemplateRouteImport } from './routes/settings/templates/template'
import { Route as SettingsTemplatesIdRouteImport } from './routes/settings/templates/$id'
import { Route as EmailVerifyCodeRouteImport } from './routes/email/verify/$code'

const WorkerLifycycleRoute = WorkerLifycycleRouteImport.update({
  id: '/worker-lifycycle',
  path: '/worker-lifycycle',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeOverviewRoute = EmployeeOverviewRouteImport.update({
  id: '/employee-overview',
  path: '/employee-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$Id',
  path: '/user/$Id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIssueStatusesRoute = SettingsIssueStatusesRouteImport.update({
  id: '/issue-statuses',
  path: '/issue-statuses',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsEngagementStatusesRoute =
  SettingsEngagementStatusesRouteImport.update({
    id: '/engagement-statuses',
    path: '/engagement-statuses',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsEmployeesRoute = SettingsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => SettingsRoute,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTemplatesTemplateRoute =
  SettingsTemplatesTemplateRouteImport.update({
    id: '/templates/template',
    path: '/templates/template',
    getParentRoute: () => SettingsRoute,
  } as any)
const SettingsTemplatesIdRoute = SettingsTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => SettingsRoute,
} as any)
const EmailVerifyCodeRoute = EmailVerifyCodeRouteImport.update({
  id: '/email/verify/$code',
  path: '/email/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/employee-overview': typeof EmployeeOverviewRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/settings/employees': typeof SettingsEmployeesRoute
  '/settings/engagement-statuses': typeof SettingsEngagementStatusesRoute
  '/settings/issue-statuses': typeof SettingsIssueStatusesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
  '/settings/templates/$id': typeof SettingsTemplatesIdRoute
  '/settings/templates/template': typeof SettingsTemplatesTemplateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee-overview': typeof EmployeeOverviewRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/settings/employees': typeof SettingsEmployeesRoute
  '/settings/engagement-statuses': typeof SettingsEngagementStatusesRoute
  '/settings/issue-statuses': typeof SettingsIssueStatusesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
  '/settings/templates/$id': typeof SettingsTemplatesIdRoute
  '/settings/templates/template': typeof SettingsTemplatesTemplateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/employee-overview': typeof EmployeeOverviewRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRouteWithChildren
  '/signup': typeof SignupRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/settings/employees': typeof SettingsEmployeesRoute
  '/settings/engagement-statuses': typeof SettingsEngagementStatusesRoute
  '/settings/issue-statuses': typeof SettingsIssueStatusesRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
  '/settings/templates/$id': typeof SettingsTemplatesIdRoute
  '/settings/templates/template': typeof SettingsTemplatesTemplateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employee-overview'
    | '/home'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/worker-lifycycle'
    | '/password/forgot'
    | '/password/reset'
    | '/settings/employees'
    | '/settings/engagement-statuses'
    | '/settings/issue-statuses'
    | '/settings/profile'
    | '/user/$Id'
    | '/email/verify/$code'
    | '/settings/templates/$id'
    | '/settings/templates/template'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employee-overview'
    | '/home'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/worker-lifycycle'
    | '/password/forgot'
    | '/password/reset'
    | '/settings/employees'
    | '/settings/engagement-statuses'
    | '/settings/issue-statuses'
    | '/settings/profile'
    | '/user/$Id'
    | '/email/verify/$code'
    | '/settings/templates/$id'
    | '/settings/templates/template'
  id:
    | '__root__'
    | '/'
    | '/employee-overview'
    | '/home'
    | '/login'
    | '/profile'
    | '/settings'
    | '/signup'
    | '/worker-lifycycle'
    | '/password/forgot'
    | '/password/reset'
    | '/settings/employees'
    | '/settings/engagement-statuses'
    | '/settings/issue-statuses'
    | '/settings/profile'
    | '/user/$Id'
    | '/email/verify/$code'
    | '/settings/templates/$id'
    | '/settings/templates/template'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmployeeOverviewRoute: typeof EmployeeOverviewRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SignupRoute: typeof SignupRoute
  WorkerLifycycleRoute: typeof WorkerLifycycleRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordResetRoute: typeof PasswordResetRoute
  UserIdRoute: typeof UserIdRoute
  EmailVerifyCodeRoute: typeof EmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-lifycycle': {
      id: '/worker-lifycycle'
      path: '/worker-lifycycle'
      fullPath: '/worker-lifycycle'
      preLoaderRoute: typeof WorkerLifycycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-overview': {
      id: '/employee-overview'
      path: '/employee-overview'
      fullPath: '/employee-overview'
      preLoaderRoute: typeof EmployeeOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$Id': {
      id: '/user/$Id'
      path: '/user/$Id'
      fullPath: '/user/$Id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/issue-statuses': {
      id: '/settings/issue-statuses'
      path: '/issue-statuses'
      fullPath: '/settings/issue-statuses'
      preLoaderRoute: typeof SettingsIssueStatusesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/engagement-statuses': {
      id: '/settings/engagement-statuses'
      path: '/engagement-statuses'
      fullPath: '/settings/engagement-statuses'
      preLoaderRoute: typeof SettingsEngagementStatusesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/employees': {
      id: '/settings/employees'
      path: '/employees'
      fullPath: '/settings/employees'
      preLoaderRoute: typeof SettingsEmployeesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/templates/template': {
      id: '/settings/templates/template'
      path: '/templates/template'
      fullPath: '/settings/templates/template'
      preLoaderRoute: typeof SettingsTemplatesTemplateRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/templates/$id': {
      id: '/settings/templates/$id'
      path: '/templates/$id'
      fullPath: '/settings/templates/$id'
      preLoaderRoute: typeof SettingsTemplatesIdRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/email/verify/$code': {
      id: '/email/verify/$code'
      path: '/email/verify/$code'
      fullPath: '/email/verify/$code'
      preLoaderRoute: typeof EmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsEmployeesRoute: typeof SettingsEmployeesRoute
  SettingsEngagementStatusesRoute: typeof SettingsEngagementStatusesRoute
  SettingsIssueStatusesRoute: typeof SettingsIssueStatusesRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTemplatesIdRoute: typeof SettingsTemplatesIdRoute
  SettingsTemplatesTemplateRoute: typeof SettingsTemplatesTemplateRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsEmployeesRoute: SettingsEmployeesRoute,
  SettingsEngagementStatusesRoute: SettingsEngagementStatusesRoute,
  SettingsIssueStatusesRoute: SettingsIssueStatusesRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTemplatesIdRoute: SettingsTemplatesIdRoute,
  SettingsTemplatesTemplateRoute: SettingsTemplatesTemplateRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmployeeOverviewRoute: EmployeeOverviewRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SignupRoute: SignupRoute,
  WorkerLifycycleRoute: WorkerLifycycleRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordResetRoute: PasswordResetRoute,
  UserIdRoute: UserIdRoute,
  EmailVerifyCodeRoute: EmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
