/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIdRouteImport } from './routes/user/$Id'
import { Route as ProfileProfileRouteImport } from './routes/profile/profile'
import { Route as PasswordResetRouteImport } from './routes/password/reset'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as Home_indexPageRouteImport } from './routes/home_index/page'
import { Route as EmailVerifyCodeRouteImport } from './routes/email/verify/$code'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$Id',
  path: '/user/$Id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileProfileRoute = ProfileProfileRouteImport.update({
  id: '/profile/profile',
  path: '/profile/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const Home_indexPageRoute = Home_indexPageRouteImport.update({
  id: '/home_index/page',
  path: '/home_index/page',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyCodeRoute = EmailVerifyCodeRouteImport.update({
  id: '/email/verify/$code',
  path: '/email/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/home_index/page': typeof Home_indexPageRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/profile/profile': typeof ProfileProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/home_index/page': typeof Home_indexPageRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/profile/profile': typeof ProfileProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/home_index/page': typeof Home_indexPageRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/profile/profile': typeof ProfileProfileRoute
  '/user/$Id': typeof UserIdRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/home_index/page'
    | '/password/forgot'
    | '/password/reset'
    | '/profile/profile'
    | '/user/$Id'
    | '/email/verify/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/home_index/page'
    | '/password/forgot'
    | '/password/reset'
    | '/profile/profile'
    | '/user/$Id'
    | '/email/verify/$code'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/signup'
    | '/home_index/page'
    | '/password/forgot'
    | '/password/reset'
    | '/profile/profile'
    | '/user/$Id'
    | '/email/verify/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  Home_indexPageRoute: typeof Home_indexPageRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordResetRoute: typeof PasswordResetRoute
  ProfileProfileRoute: typeof ProfileProfileRoute
  UserIdRoute: typeof UserIdRoute
  EmailVerifyCodeRoute: typeof EmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$Id': {
      id: '/user/$Id'
      path: '/user/$Id'
      fullPath: '/user/$Id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/profile': {
      id: '/profile/profile'
      path: '/profile/profile'
      fullPath: '/profile/profile'
      preLoaderRoute: typeof ProfileProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home_index/page': {
      id: '/home_index/page'
      path: '/home_index/page'
      fullPath: '/home_index/page'
      preLoaderRoute: typeof Home_indexPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/verify/$code': {
      id: '/email/verify/$code'
      path: '/email/verify/$code'
      fullPath: '/email/verify/$code'
      preLoaderRoute: typeof EmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  Home_indexPageRoute: Home_indexPageRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordResetRoute: PasswordResetRoute,
  ProfileProfileRoute: ProfileProfileRoute,
  UserIdRoute: UserIdRoute,
  EmailVerifyCodeRoute: EmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
