/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerLifycycleRouteImport } from './routes/worker-lifycycle'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RegisterOrgRouteImport } from './routes/register-org'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrgSettingsRouteImport } from './routes/org-settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmployeeOverviewRouteImport } from './routes/employee-overview'
import { Route as TemplateRouteRouteImport } from './routes/template/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateIndexRouteImport } from './routes/template/index'
import { Route as UserIdRouteImport } from './routes/user/$Id'
import { Route as TemplateTemplateIdRouteImport } from './routes/template/$templateId'
import { Route as PasswordResetRouteImport } from './routes/password/reset'
import { Route as PasswordForgotRouteImport } from './routes/password/forgot'
import { Route as EmailVerifyCodeRouteImport } from './routes/email/verify/$code'

const WorkerLifycycleRoute = WorkerLifycycleRouteImport.update({
  id: '/worker-lifycycle',
  path: '/worker-lifycycle',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterOrgRoute = RegisterOrgRouteImport.update({
  id: '/register-org',
  path: '/register-org',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/org-settings',
  path: '/org-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeOverviewRoute = EmployeeOverviewRouteImport.update({
  id: '/employee-overview',
  path: '/employee-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateRouteRoute = TemplateRouteRouteImport.update({
  id: '/template',
  path: '/template',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateIndexRoute = TemplateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplateRouteRoute,
} as any)
const UserIdRoute = UserIdRouteImport.update({
  id: '/user/$Id',
  path: '/user/$Id',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateTemplateIdRoute = TemplateTemplateIdRouteImport.update({
  id: '/$templateId',
  path: '/$templateId',
  getParentRoute: () => TemplateRouteRoute,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordForgotRoute = PasswordForgotRouteImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailVerifyCodeRoute = EmailVerifyCodeRouteImport.update({
  id: '/email/verify/$code',
  path: '/email/verify/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/template': typeof TemplateRouteRouteWithChildren
  '/employee-overview': typeof EmployeeOverviewRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/org-settings': typeof OrgSettingsRoute
  '/profile': typeof ProfileRoute
  '/register-org': typeof RegisterOrgRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/user/$Id': typeof UserIdRoute
  '/template/': typeof TemplateIndexRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/employee-overview': typeof EmployeeOverviewRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/org-settings': typeof OrgSettingsRoute
  '/profile': typeof ProfileRoute
  '/register-org': typeof RegisterOrgRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/user/$Id': typeof UserIdRoute
  '/template': typeof TemplateIndexRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/template': typeof TemplateRouteRouteWithChildren
  '/employee-overview': typeof EmployeeOverviewRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/org-settings': typeof OrgSettingsRoute
  '/profile': typeof ProfileRoute
  '/register-org': typeof RegisterOrgRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/worker-lifycycle': typeof WorkerLifycycleRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/user/$Id': typeof UserIdRoute
  '/template/': typeof TemplateIndexRoute
  '/email/verify/$code': typeof EmailVerifyCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/template'
    | '/employee-overview'
    | '/home'
    | '/login'
    | '/org-settings'
    | '/profile'
    | '/register-org'
    | '/settings'
    | '/signup'
    | '/worker-lifycycle'
    | '/password/forgot'
    | '/password/reset'
    | '/template/$templateId'
    | '/user/$Id'
    | '/template/'
    | '/email/verify/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employee-overview'
    | '/home'
    | '/login'
    | '/org-settings'
    | '/profile'
    | '/register-org'
    | '/settings'
    | '/signup'
    | '/worker-lifycycle'
    | '/password/forgot'
    | '/password/reset'
    | '/template/$templateId'
    | '/user/$Id'
    | '/template'
    | '/email/verify/$code'
  id:
    | '__root__'
    | '/'
    | '/template'
    | '/employee-overview'
    | '/home'
    | '/login'
    | '/org-settings'
    | '/profile'
    | '/register-org'
    | '/settings'
    | '/signup'
    | '/worker-lifycycle'
    | '/password/forgot'
    | '/password/reset'
    | '/template/$templateId'
    | '/user/$Id'
    | '/template/'
    | '/email/verify/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplateRouteRoute: typeof TemplateRouteRouteWithChildren
  EmployeeOverviewRoute: typeof EmployeeOverviewRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterOrgRoute: typeof RegisterOrgRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  WorkerLifycycleRoute: typeof WorkerLifycycleRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordResetRoute: typeof PasswordResetRoute
  UserIdRoute: typeof UserIdRoute
  EmailVerifyCodeRoute: typeof EmailVerifyCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker-lifycycle': {
      id: '/worker-lifycycle'
      path: '/worker-lifycycle'
      fullPath: '/worker-lifycycle'
      preLoaderRoute: typeof WorkerLifycycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register-org': {
      id: '/register-org'
      path: '/register-org'
      fullPath: '/register-org'
      preLoaderRoute: typeof RegisterOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-settings': {
      id: '/org-settings'
      path: '/org-settings'
      fullPath: '/org-settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-overview': {
      id: '/employee-overview'
      path: '/employee-overview'
      fullPath: '/employee-overview'
      preLoaderRoute: typeof EmployeeOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template': {
      id: '/template'
      path: '/template'
      fullPath: '/template'
      preLoaderRoute: typeof TemplateRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/': {
      id: '/template/'
      path: '/'
      fullPath: '/template/'
      preLoaderRoute: typeof TemplateIndexRouteImport
      parentRoute: typeof TemplateRouteRoute
    }
    '/user/$Id': {
      id: '/user/$Id'
      path: '/user/$Id'
      fullPath: '/user/$Id'
      preLoaderRoute: typeof UserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$templateId': {
      id: '/template/$templateId'
      path: '/$templateId'
      fullPath: '/template/$templateId'
      preLoaderRoute: typeof TemplateTemplateIdRouteImport
      parentRoute: typeof TemplateRouteRoute
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/verify/$code': {
      id: '/email/verify/$code'
      path: '/email/verify/$code'
      fullPath: '/email/verify/$code'
      preLoaderRoute: typeof EmailVerifyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TemplateRouteRouteChildren {
  TemplateTemplateIdRoute: typeof TemplateTemplateIdRoute
  TemplateIndexRoute: typeof TemplateIndexRoute
}

const TemplateRouteRouteChildren: TemplateRouteRouteChildren = {
  TemplateTemplateIdRoute: TemplateTemplateIdRoute,
  TemplateIndexRoute: TemplateIndexRoute,
}

const TemplateRouteRouteWithChildren = TemplateRouteRoute._addFileChildren(
  TemplateRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplateRouteRoute: TemplateRouteRouteWithChildren,
  EmployeeOverviewRoute: EmployeeOverviewRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  ProfileRoute: ProfileRoute,
  RegisterOrgRoute: RegisterOrgRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  WorkerLifycycleRoute: WorkerLifycycleRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordResetRoute: PasswordResetRoute,
  UserIdRoute: UserIdRoute,
  EmailVerifyCodeRoute: EmailVerifyCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
