// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";
import { POSTGRES_URI } from "./src/constants/env";

export default defineConfig({
    schema: "./src/prisma/schema.prisma",
    migrations: {
        path: "src/prisma/migrations",
        seed: "ts-node src/prisma/seed.ts",
    },
    datasource: {
        url: POSTGRES_URI, // create custom type file later
    },
});
